{{- if .Values.configMap.enabled -}}
{{- range $key, $data := .Values.configMap.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project.name" $ }}-{{ $key }}
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "project.labels" $ | nindent 4 }}
    {{- include "util.toYaml" ( dict "value" $.Values.configMap.labels "indent" 4 ) }}
  annotations:
    {{- include "util.toYaml" ( dict "value" $.Values.configMap.annotations "indent" 4 ) }}
data:
  {{- range $dataKey, $dataValue := $data }}
  {{ $dataKey }}: {{ $dataValue | quote }}
  {{- end }}
{{- end }}
{{- end }}