{{- if and .Values.autoscaling.enabled .Values.deployment.enabled }}
---
{{- if .Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler" }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "project.name" . }}
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    {{- include "util.toYaml" ( dict "value" .Values.autoscaling.labels "indent" 4 ) }}
  annotations:
    {{- include "util.toYaml" ( dict "value" .Values.autoscaling.annotations "indent" 4 ) }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "project.name" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- include "util.toYaml" ( dict "value" .Values.autoscaling.metrics "indent" 4 ) }}
  {{- if .Values.autoscaling.behavior }}
  behavior:
    {{- include "util.toYaml" ( dict "value" .Values.autoscaling.behavior "indent" 4 ) }}
  {{- end }}
{{- end }}