{{- if .Values.networkPolicy.enabled }}
---
apiVersion: "networking.k8s.io/v1"
kind: NetworkPolicy
metadata:
  name: {{ include "project.name" . }}
  namespace: {{ include "project.namespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    {{- include "util.toYaml" ( dict "value" .Values.networkPolicy.labels "indent" 4 ) }}
  annotations:
    {{- include "util.toYaml" ( dict "value" .Values.networkPolicy.annotations "indent" 4 ) }}
spec:
  selector:
    matchLabels:
      {{- include "project.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- include "util.toYaml" ( dict "value" .Values.networkPolicy.ingress "indent" 4 ) }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- include "util.toYaml" ( dict "value" .Values.networkPolicy.egress "indent" 4 ) }}
  {{- end }}
{{- end }}