{{- if .Values.secret.enabled -}}
{{- range $key, $data := .Values.secret.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "project.name" $ }}-{{ $key }}
  namespace: {{ include "project.namespace" $ }}
  labels:
    {{- include "project.labels" $ | nindent 4 }}
    {{- include "util.toYaml" ( dict "value" $.Values.secret.labels "indent" 4 ) }}
    {{- include "util.toYaml" ( dict "value" $data.labels "indent" 4 ) }}
  annotations:
    {{- include "util.toYaml" ( dict "value" $.Values.secret.annotations "indent" 4 ) }}
    {{- include "util.toYaml" ( dict "value" $data.annotations "indent" 4 ) }}
type: {{ $data.type }}
data:
  {{- range $key, $value := $data.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
